#define Pshmem_my_pe  pshmem_my_pe 
#define Pshmem_n_pes  pshmem_n_pes 
#define Pshmem_short_put  pshmem_short_put 
#define Pshmem_int_put  pshmem_int_put 
#define Pshmem_long_put  pshmem_long_put 
#define Pshmem_longlong_put  pshmem_longlong_put 
#define Pshmem_longdouble_put  pshmem_longdouble_put 
#define Pshmem_double_put  pshmem_double_put 
#define Pshmem_float_put  pshmem_float_put 
#define Pshmem_putmem  pshmem_putmem 
#define Pshmem_put32  pshmem_put32 
#define Pshmem_put64  pshmem_put64 
#define Pshmem_put128  pshmem_put128 
#define Pshmem_short_get  pshmem_short_get 
#define Pshmem_int_get  pshmem_int_get 
#define Pshmem_long_get  pshmem_long_get 
#define Pshmem_longlong_get  pshmem_longlong_get 
#define Pshmem_longdouble_get  pshmem_longdouble_get 
#define Pshmem_double_get  pshmem_double_get 
#define Pshmem_float_get  pshmem_float_get 
#define Pshmem_getmem  pshmem_getmem 
#define Pshmem_get32  pshmem_get32 
#define Pshmem_get64  pshmem_get64 
#define Pshmem_get128  pshmem_get128 
#define Pshmem_char_p  pshmem_char_p 
#define Pshmem_short_p  pshmem_short_p 
#define Pshmem_int_p  pshmem_int_p 
#define Pshmem_long_p  pshmem_long_p 
#define Pshmem_longlong_p  pshmem_longlong_p 
#define Pshmem_float_p  pshmem_float_p 
#define Pshmem_double_p  pshmem_double_p 
#define Pshmem_longdouble_p  pshmem_longdouble_p 
#define Pshmem_char_g  pshmem_char_g 
#define Pshmem_short_g  pshmem_short_g 
#define Pshmem_int_g  pshmem_int_g 
#define Pshmem_long_g  pshmem_long_g 
#define Pshmem_longlong_g  pshmem_longlong_g 
#define Pshmem_float_g  pshmem_float_g 
#define Pshmem_double_g  pshmem_double_g 
#define Pshmem_longdouble_g  pshmem_longdouble_g 
#define Pshmem_double_iput  pshmem_double_iput 
#define Pshmem_float_iput  pshmem_float_iput 
#define Pshmem_int_iput  pshmem_int_iput 
#define Pshmem_iput32  pshmem_iput32 
#define Pshmem_iput64  pshmem_iput64 
#define Pshmem_iput128  pshmem_iput128 
#define Pshmem_long_iput  pshmem_long_iput 
#define Pshmem_longdouble_iput  pshmem_longdouble_iput 
#define Pshmem_longlong_iput  pshmem_longlong_iput 
#define Pshmem_short_iput  pshmem_short_iput 
#define Pshmem_double_iget  pshmem_double_iget 
#define Pshmem_float_iget  pshmem_float_iget 
#define Pshmem_int_iget  pshmem_int_iget 
#define Pshmem_iget32  pshmem_iget32 
#define Pshmem_iget64  pshmem_iget64 
#define Pshmem_iget128  pshmem_iget128 
#define Pshmem_long_iget  pshmem_long_iget 
#define Pshmem_longdouble_iget  pshmem_longdouble_iget 
#define Pshmem_longlong_iget  pshmem_longlong_iget 
#define Pshmem_short_iget  pshmem_short_iget 
#define Pshmem_barrier_all  pshmem_barrier_all 
#define Pshmem_barrier  pshmem_barrier 
#define Pshmem_fence  pshmem_fence 
#define Pshmem_quiet  pshmem_quiet 
#define Pshmem_pe_accessible  pshmem_pe_accessible 
#define Pshmem_addr_accessible  pshmem_addr_accessible 
#define Pshmem_ptr  pshmem_ptr 
#define Pshmemalign  pshmemalign 
#define Pshmem_short_wait_until  pshmem_short_wait_until 
#define Pshmem_int_wait_until  pshmem_int_wait_until 
#define Pshmem_long_wait_until  pshmem_long_wait_until 
#define Pshmem_longlong_wait_until  pshmem_longlong_wait_until 
#define Pshmem_wait_until  pshmem_wait_until 
#define Pshmem_short_wait  pshmem_short_wait 
#define Pshmem_int_wait  pshmem_int_wait 
#define Pshmem_long_wait  pshmem_long_wait 
#define Pshmem_longlong_wait  pshmem_longlong_wait 
#define Pshmem_wait  pshmem_wait 
#define Pshmem_int_swap  pshmem_int_swap 
#define Pshmem_long_swap  pshmem_long_swap 
#define Pshmem_longlong_swap  pshmem_longlong_swap 
#define Pshmem_float_swap  pshmem_float_swap 
#define Pshmem_double_swap  pshmem_double_swap 
#define Pshmem_swap  pshmem_swap 
#define Pshmem_int_cswap  pshmem_int_cswap 
#define Pshmem_long_cswap  pshmem_long_cswap 
#define Pshmem_longlong_cswap  pshmem_longlong_cswap 
#define Pshmem_int_fadd  pshmem_int_fadd 
#define Pshmem_long_fadd  pshmem_long_fadd 
#define Pshmem_longlong_fadd  pshmem_longlong_fadd 
#define Pshmem_int_finc  pshmem_int_finc 
#define Pshmem_long_finc  pshmem_long_finc 
#define Pshmem_longlong_finc  pshmem_longlong_finc 
#define Pshmem_int_add  pshmem_int_add 
#define Pshmem_long_add  pshmem_long_add 
#define Pshmem_longlong_add  pshmem_longlong_add 
#define Pshmem_int_inc  pshmem_int_inc 
#define Pshmem_long_inc  pshmem_long_inc 
#define Pshmem_longlong_inc  pshmem_longlong_inc 
#define Pshmem_clear_cache_inv  pshmem_clear_cache_inv 
#define Pshmem_set_cache_inv  pshmem_set_cache_inv 
#define Pshmem_clear_cache_line_inv  pshmem_clear_cache_line_inv 
#define Pshmem_set_cache_line_inv  pshmem_set_cache_line_inv 
#define Pshmem_udcflush  pshmem_udcflush 
#define Pshmem_udcflush_line  pshmem_udcflush_line 
#define Pshmem_complexd_sum_to_all  pshmem_complexd_sum_to_all 
#define Pshmem_complexf_sum_to_all  pshmem_complexf_sum_to_all 
#define Pshmem_double_sum_to_all  pshmem_double_sum_to_all 
#define Pshmem_float_sum_to_all  pshmem_float_sum_to_all 
#define Pshmem_int_sum_to_all  pshmem_int_sum_to_all 
#define Pshmem_long_sum_to_all  pshmem_long_sum_to_all 
#define Pshmem_longdouble_sum_to_all  pshmem_longdouble_sum_to_all 
#define Pshmem_longlong_sum_to_all  pshmem_longlong_sum_to_all 
#define Pshmem_short_sum_to_all  pshmem_short_sum_to_all 
#define Pshmem_complexd_prod_to_all  pshmem_complexd_prod_to_all 
#define Pshmem_complexf_prod_to_all  pshmem_complexf_prod_to_all 
#define Pshmem_double_prod_to_all  pshmem_double_prod_to_all 
#define Pshmem_float_prod_to_all  pshmem_float_prod_to_all 
#define Pshmem_int_prod_to_all  pshmem_int_prod_to_all 
#define Pshmem_long_prod_to_all  pshmem_long_prod_to_all 
#define Pshmem_longdouble_prod_to_all  pshmem_longdouble_prod_to_all 
#define Pshmem_longlong_prod_to_all  pshmem_longlong_prod_to_all 
#define Pshmem_short_prod_to_all  pshmem_short_prod_to_all 
#define Pshmem_int_and_to_all  pshmem_int_and_to_all 
#define Pshmem_long_and_to_all  pshmem_long_and_to_all 
#define Pshmem_longlong_and_to_all  pshmem_longlong_and_to_all 
#define Pshmem_short_and_to_all  pshmem_short_and_to_all 
#define Pshmem_int_or_to_all  pshmem_int_or_to_all 
#define Pshmem_long_or_to_all  pshmem_long_or_to_all 
#define Pshmem_longlong_or_to_all  pshmem_longlong_or_to_all 
#define Pshmem_short_or_to_all  pshmem_short_or_to_all 
#define Pshmem_int_xor_to_all  pshmem_int_xor_to_all 
#define Pshmem_long_xor_to_all  pshmem_long_xor_to_all 
#define Pshmem_longlong_xor_to_all  pshmem_longlong_xor_to_all 
#define Pshmem_short_xor_to_all  pshmem_short_xor_to_all 
#define Pshmem_int_max_to_all  pshmem_int_max_to_all 
#define Pshmem_long_max_to_all  pshmem_long_max_to_all 
#define Pshmem_longlong_max_to_all  pshmem_longlong_max_to_all 
#define Pshmem_short_max_to_all  pshmem_short_max_to_all 
#define Pshmem_longdouble_max_to_all  pshmem_longdouble_max_to_all 
#define Pshmem_float_max_to_all  pshmem_float_max_to_all 
#define Pshmem_double_max_to_all  pshmem_double_max_to_all 
#define Pshmem_int_min_to_all  pshmem_int_min_to_all 
#define Pshmem_long_min_to_all  pshmem_long_min_to_all 
#define Pshmem_longlong_min_to_all  pshmem_longlong_min_to_all 
#define Pshmem_short_min_to_all  pshmem_short_min_to_all 
#define Pshmem_longdouble_min_to_all  pshmem_longdouble_min_to_all 
#define Pshmem_float_min_to_all  pshmem_float_min_to_all 
#define Pshmem_double_min_to_all  pshmem_double_min_to_all 
#define Pshmem_broadcast32  pshmem_broadcast32 
#define Pshmem_broadcast64  pshmem_broadcast64 
#define Pshmem_fcollect32  pshmem_fcollect32 
#define Pshmem_fcollect64  pshmem_fcollect64 
#define Pshmem_collect32  pshmem_collect32 
#define Pshmem_collect64  pshmem_collect64 
#define Pshmem_set_lock  pshmem_set_lock 
#define Pshmem_clear_lock  pshmem_clear_lock 
#define Pshmem_test_lock  pshmem_test_lock 
#define Pshmem_malloc  pshmem_malloc
#define Pshmem_realloc  pshmem_realloc
#define Pshmem_free  pshmem_free
#define Pshmem_align  pshmem_align
#define Pshmem_sync  pshmem_sync
#define Pshmem_sync_all  pshmem_sync_all
#define P_num_pes  p_num_pes
#define P_my_pe  p_my_pe
